<?php

namespace JekyllScout\Writer;

use org\bovigo\vfs\vfsStream;
use Symfony\Component\Filesystem\Filesystem;

class PageWriterTest extends \PHPUnit_Framework_TestCase
{
    private $pageWriter;

    public function setUp()
    {
        $this->pageWriter = new PageWriter(new Filesystem());

        vfsStream::setup('root');
    }

    public function testPrepareCreatesDirectory()
    {
        $path = vfsStream::url('root/_articles');
        $this->pageWriter->prepare($path);

        $this->assertTrue(is_dir($path));
    }

    public function testWriteWithEmptyFrontmatter()
    {
        $path = vfsStream::url('root/test.html');
        $this->pageWriter->write($path, '<p></p>', array());

        $this->assertSame('<p></p>', file_get_contents($path));
    }

    public function testWriteWithFrontmatter()
    {
        $path = vfsStream::url('root/test.html');
        $this->pageWriter->write($path, '<p></p>', array(
            'name' => 'Test',
            'number' => 123,
        ));

        $expectedContents = <<<'PAGE'
---
# This file was auto-generated by jekyllscout
name: Test
number: 123
---
<p></p>
PAGE;

        $this->assertSame($expectedContents, file_get_contents($path));
    }
}
