<?php

namespace JekyllScout\Writer;

use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Yaml\Yaml;

class PageWriter
{
    /**
     * @var Filesystem
     */
    private $filesystem;

    /**
     * @param string Filesystem
     */
    public function __construct(Filesystem $filesystem)
    {
        $this->filesystem = $filesystem;
    }

    /**
     * @param string $path
     */
    public function prepare($path)
    {
        if ($this->filesystem->exists($path)) {
            $this->filesystem->remove($path);
        }

        $this->filesystem->mkdir($path);
    }

    /**
     * @param string $path
     * @param string $content
     * @param array $frontmatter
     */
    public function write($path, $content, array $frontmatter)
    {
        $frontmatterString = '';
        if (!empty($frontmatter)) {
            $frontmatterString = sprintf(
                "---\n# %s\n%s---\n",
                $this->generatedMessage(),
                Yaml::dump($frontmatter)
            );
        }

        file_put_contents($path, $frontmatterString . $content);
    }

    /**
     * @return string
     */
    private function generatedMessage()
    {
        return 'This file was auto-generated by jekyllscout';
    }
}
